apiVersion: v1
kind: Pod
metadata:
   name: mynginxpod
spec:
   containers:
    - image: nginx
      name: mynginxcontainer
      ports:
       - containerPort: 80     
      volumeMounts:
            - name: myconfigvolume
              mountPath: /etc/nginx/conf.d/
   volumes:
       - name:  myconfigvolume
         configMap: 
                name: mynginxconf
