apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonsetwala
spec:
  selector:
    matchLabels:
      app: sshd
  template:
    metadata:
      labels:
        app: sshd
    spec:
       containers:
       - image: luksa/sshd-monitor
         name: sshd
