apiVersion: batch/v1
kind: Job
metadata:
  name: batch
spec:
  completions: 5
  parallelism: 2
  template:
    metadata:
      labels:
        app: batch
    spec:
       restartPolicy: OnFailure
       containers:
       - image: luksa/batch-job
         name: batch
