apiVersion: v1
kind: Pod
metadata:
   name: mynginxpod1
   labels:
      env: facebook
spec:
   containers:
    - image: nginx
      name: mynginxcontainer
      ports:
       - containerPort: 80     
         hostPort: 80
