apiVersion: v1
kind: Pod
metadata:
   name: mynginxpod
   namespace: myns
   labels:
      app: facebook
spec:
   containers:
    - image: nginx
      name: mynginxcontainer
      ports:
       - containerPort: 80     
