apiVersion: v1
kind: Pod
metadata:
   name: emptywalappod
spec:
   containers:
      - image: nginx
        name: ngcontainer
        volumeMounts:
              - name: htmlfolder
                mountPath: /usr/share/nginx/html
   volumes:
    - name: htmlfolder
      nfs:
       server: fs-0ec6dc0da7c39de7b.efs.ap-south-1.amazonaws.com
       path: /test
