apiVersion: v1
kind: Pod
metadata:
   name: mynginxpod
   labels:
      env: live
spec:  
   nodeSelector:
       gpu: "true1"
   containers:
    - image: nginx
      name: mynginxcontainer
      ports:
       - containerPort: 80
         hostPort: 80
