apiVersion: v1
kind: Pod
metadata:
   name: mysqlpod
spec:
   containers:
    - image: mysql
      name: mynginxcontainer
      ports:
       - containerPort: 3306
      env:
       - name: MYSQL_ROOT_PASSWORD
         valueFrom:
            secretKeyRef:
                 name: mysqlsecret
                 key: MYSQL_ROOT_PASSWORD     
